# Generated by Django 2.1.3 on 2021-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
            ],
        ),
    ]
