# Generated by Django 2.1.3 on 2021-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_ingredients'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(to='food.Food'),
        ),
    ]
