# Generated by Django 2.1.3 on 2021-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20211211_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, to='food.Food'),
        ),
    ]
