# Generated by Django 2.1.3 on 2021-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211213_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'waiting'), (1, 'released')], default='waiting', max_length=10),
        ),
    ]
